//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autentificación.modelos.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado_Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado_Requerimiento()
        {
            this.Requerimientos = new HashSet<Requerimientos>();
        }
    
        public int Id_Estado { get; set; }
        public string Descripcion { get; set; }
        public int UsuarioId_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimientos> Requerimientos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
